on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Theory
    steps:
      - uses: actions/checkout@v3
      - uses: cplaursen/isabelle-theory-build-github-action@main
        with:
          isabelle-url: 'https://github.com/seL4/isabelle/archive/refs/tags/Isabelle2025.tar.gz'
          report_url: 'https://isabelle-utp-ci-dashboard.link/submit_job_log'
          report_secret: ${{ secrets.DashboardReportKey }}
